# Generated by Django 6.0.3 on 2026-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_datasetrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
