# Generated by Django 4.1.4 on 2026-04-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_file_file_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDownload',
        ),
    ]
